# Generated by Django 3.2.12 on 2022-09-07 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_voter_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.imageotp'),
        ),
    ]
